Repository BlckHawker/Productivity-App, pull requests merged in 2025-09, with the labels that each got.

#75 [Bugfix] Fix project plan formatting
  CHANGELOG.md
  PROJECT PLAN.md
Labels: bug

#94 [Feature] Add util scripts to configure for testing and running build
  CHANGELOG.md
  WIKI.md
  backend/package.json
  backend/scripts/change-imports.ts
  backend/src/router.ts
  backend/src/utils.ts
Labels: enhancement, backend

#91 Add Swagger API
  .github/workflows/coverage.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  backend/jest.config.json
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/task.ts
  backend/src/requestHandlers/task.ts
  backend/src/router.ts
  backend/src/server.ts
  backend/src/services/task.ts
  backend/src/swagger.ts
  backend/src/utils.ts
  backend/tests/src/requestHandlers/task.test.ts
  backend/tsconfig.json
  frontend/package-lock.json
  package-lock.json
Labels: documentation, enhancement, backend

#98 Remove `package-lock.json`s from git history
  .gitignore
  CHANGELOG.md
  backend/package-lock.json
  frontend/package-lock.json
  package-lock.json
Labels: enhancement

#118 [Feature] ESLint Rule Implementation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/bugfix.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .prettierignore
  .prettierrc
  CHANGELOG.md
  PROJECT PLAN.md
  README.md
  WIKI.md
  backend/babel.config.js
  backend/jest.config.json
  backend/package.json
  backend/scripts/change-imports.ts
  backend/scripts/clear-db.ts
  backend/scripts/expand-env.ts
  backend/scripts/seed-db.ts
  backend/src/controllers/project.ts
  backend/src/prisma.ts
  backend/src/requestHandlers/project.ts
  backend/src/router.ts
  backend/src/server.ts
  backend/src/services/project.ts
  backend/src/swagger.ts
  backend/src/types/express.d.ts
  backend/src/utils.ts
  backend/tests/src/controllers/project.test.ts
  backend/tests/src/requestHandlers/project.test.ts
  backend/tests/src/utils.test.ts
  backend/tsconfig.json
  eslint.config.ts
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/api/task.ts
  frontend/src/api/utils.ts
  frontend/src/index.css
  frontend/src/interfaces.ts
  frontend/src/main.tsx
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  package.json
Labels: enhancement
